<h1>Paquetes utilizados</h1>

In [3]:
import numpy as np

<h1>Tarea 18-junio-2022
</h1>


<h3>Datasets utilizados</h3>

In [1]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

2022-06-25 17:34:05.875939: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-25 17:34:05.875969: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


11490434/11490434 [==============================] - 19s 2us/step


<h3>Problema:</h3>
Dentro del conjunto de datos, seleccióne la esquina inferior que contenga  14×14  píxeles en cada una de las imágenes y visualice una de ellas.

In [7]:
my_slice_problem = train_images[:,14:,14:]
print(my_slice_problem[-1])

[[ 97 254 252 146  52   0   0   0   0   0   0   0   0   0]
 [232 181  60   0   0   0   0   0   0   0   0   0   0   0]
 [ 46   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0]]


<h3>Problema:</h3>
Escriba un código en Python que devuelva el máximo valor de un vector.

In [3]:
def max_vector1D(arr):
    maximo = max(arr)
    #maximo = np.max(np.array(arr))
    return maximo
max_vector1D([1,2,3,4])

4

<h3>Problema: </h3>
<p
 style='font-size:16px'
>
Creen una clase Point en coordenadas cartesianas, que se su constructor inicialice el objeto a un punto con unas coordenadas dadas. Además, la clase debe contener dos métodos:

translate(), que reciba como argumentos dos valores arbitrarios  (𝑥,𝑦) .
__str__(self): que imprima el punto en precisión de coma flotante.
</p>

In [25]:
class Point:
    def __init__(self,x=0,y=0):
        self.axisx = x
        self.axisy = y
    def translate(self,deltax,deltay):
        self.axisx += deltax
        self.axisy += deltay
        
    def __str__(self):
        return f'Point coordinates: {(self.axisx,self.axisy)}'
    
objetoEjemplo2 = Point()
objetoEjemplo2.translate(4,5.5)
objetoEjemplo2.__str__()
    

'Point coordinates: (4, 5.5)'